### ISSUE TITLE
macOS 10.13 timesync is enabled yet I see false

### ISSUE THREAD

**Issue by fogonthedowns** [fjl/os-timesync#6]
`os-timesync` Library produces bad result.
```
> timesync.checkEnabled(function (err, enabled) {
...     if (err) {
.....         console.log("can't check: " + err.toString());
.....         return;
.....     }
...     console.log("enabled =", enabled);
... });
undefined
> enabled = false
```
<img width="631" alt="screen shot 2017-09-29 at 08 19 43" src="https://user-images.githubusercontent.com/142996/31022881-00d723c8-a4ef-11e7-89bb-cf7bda1cbce6.png">

**Comment by fjl** [comment]
I've looked into this and Apple made it much harder to get the setting.

In previous versions of macOS, the `ntpd` process was launched via `launchd` when the box
was checked. In 10.13 time sync is managed by `timed`, which is always running. Communication with `timed` happens via XPC. I've tried various ways of interacting with it, but there are a few issues:

* Unprivileged users can't talk to `timed`.
* The `systemsetup` command sends the XPC message `{"TMCommand":"TMIsAutomaticTimeEnabled"}`, but when I send it from nodejs `timed` just closes the connection.
